import React from "react";
import Autocomplete from "../components/Autocomplete";


function StartToYourFood() {
  const places = [
    { id: 1, name: 'Anantapur' },
    { id: 2, name: 'Chittoor' },
    { id: 3, name: 'East Godavari' },
    { id: 4, name: 'Guntur' },
    { id: 5, name: 'Krishna' },
    { id: 6, name: 'Kurnool' },
    { id: 7, name: 'Nellore' },
    { id: 8, name: 'Prakasam' },
    { id: 9, name: 'Srikakulam' },
    { id: 10, name: 'Visakhapatnam' },
    { id: 11, name: 'Vizianagaram' },
    { id: 12, name: 'West Godavari' },
    { id: 13, name: 'YSR Kadapa' },
    { id: 14, name: 'Adoni' },
    { id: 15, name: 'Amalapuram' },
    { id: 16, name: 'Bhimavaram' },
    { id: 17, name: 'Chilakaluripet' },
    { id: 18, name: 'Chirala' },
    { id: 19, name: 'Dharmavaram' },
    { id: 20, name: 'Eluru' },
    { id: 21, name: 'Gudivada' },
    { id: 22, name: 'Gudur' },
    { id: 23, name: 'Hindupur' },
    { id: 24, name: 'Kadiri' },
    { id: 25, name: 'Kakinada' },
    { id: 26, name: 'Kavali' },
    { id: 27, name: 'Machilipatnam' },
    { id: 28, name: 'Madanapalle' },
    { id: 29, name: 'Nandyal' },
    { id: 30, name: 'Narasaraopet' },
    { id: 31, name: 'Narsapuram' },
    { id: 32, name: 'Ongole' },
    { id: 33, name: 'Proddatur' },
    { id: 34, name: 'Puttur' },
    { id: 35, name: 'Rajahmundry' },
    { id: 36, name: 'Srikakulam' },
    { id: 37, name: 'Tadepalligudem' },
    { id: 38, name: 'Tadipatri' },
    { id: 39, name: 'Tenali' },
    { id: 40, name: 'Tirupati' },
    { id: 41, name: 'Tuni' },
    { id: 42, name: 'Uravakonda' },
    { id: 43, name: 'Venkatagiri' },
    { id: 44, name: 'Vijayawada' },
    { id: 45, name: 'Vinukonda' },
    { id: 46, name: 'Yemmiganur' },
    { id: 47, name: 'Yerraguntla' },
    { id: 48, name: 'Achanta' },
    { id: 49, name: 'Addanki' },
    { id: 50, name: 'Adoni' },
    { id: 51, name: 'Allagadda' },
    { id: 52, name: 'Amalapuram' },
    { id: 53, name: 'Anakapalle' },
    { id: 54, name: 'Anantapur' },
    { id: 55, name: 'Atmakur' },
    { id: 56, name: 'Avanigadda' },
    { id: 57, name: 'Badvel' },
    { id: 58, name: 'Banganapalle' },
    { id: 59, name: 'Bapatla' },
    { id: 60, name: 'Bellampalle' },
    { id: 61, name: 'Bethamcherla' },
    { id: 62, name: 'Bhattiprolu' },
    { id: 63, name: 'Bhimavaram' },
    { id: 64, name: 'Bobbili' },
    { id: 65, name: 'Chilakaluripet' },
    { id: 66, name: 'Chinnachowk' },
    { id: 67, name: 'Chittoor' },
    { id: 68, name: 'Darsi' },
    { id: 69, name: 'Dharmavaram' },
    { id: 70, name: 'Eluru' },
    { id: 71, name: 'Gadwal' },
    { id: 72, name: 'Gudivada' },
    { id: 73, name: 'Gudur' },
    { id: 74, name: 'Guntakal' },
    { id: 75, name: 'Guntur' },
    { id: 76, name: 'Hindupur' },
    { id: 77, name: 'Ichchapuram' },
    { id: 78, name: 'Jaggayyapeta' },
    { id: 79, name: 'Jammalamadugu' },
    { id: 80, name: 'Kadapa' },
    { id: 81, name: 'Kadiri' },
    { id: 82, name: 'Kakinada' },
    { id: 83, name: 'Kandukur' },
    { id: 84, name: 'Kanigiri' },
    { id: 85, name: 'Kavali' },
    { id: 86, name: 'Kovvur' },
    { id: 87, name: 'Kovur' },
    { id: 88, name: 'Kurnool' },
    { id: 89, name: 'Machilipatnam' },
    { id: 90, name: 'Madanapalle' },
    { id: 91, name: 'Mandapeta' },
    { id: 92, name: 'Mangalagiri' },
    { id: 93, name: 'Markapur' },
    { id: 94, name: 'Nagari' },
    { id: 95, name: 'Nagireddipalle' },
    { id: 96, name: 'Nandigama' },
    { id: 97, name: 'Nandyal' },
    { id: 98, name: 'Narasapur' },
    { id: 99, name: 'Narasaraopet' },
    { id: 100, name: 'Narsipatnam' },
    { id: 101, name: 'Nellore' },
    { id: 102, name: 'Nidadavole' },
    { id: 103, name: 'Nuzvid' },
    { id: 104, name: 'Ongole' },
    { id: 105, name: 'Paderu' },
    { id: 106, name: 'Palacole' },
    { id: 107, name: 'Palasa' },
    { id: 108, name: 'Palkonda' },
    { id: 109, name: 'Palwancha' },
    { id: 110, name: 'Parvathipuram' },
    { id: 111, name: 'Pedana' },
    { id: 112, name: 'Peddapuram' },
    { id: 113, name: 'Penukonda' },
    { id: 114, name: 'Pithapuram' },
    { id: 115, name: 'Ponnur' },
    { id: 116, name: 'Proddatur' },
    { id: 117, name: 'Pulivendla' },
    { id: 118, name: 'Puttur' },
    { id: 119, name: 'Rajahmundry' },
    { id: 120, name: 'Rajampet' },
    { id: 121, name: 'Ramachandrapuram' },
    { id: 122, name: 'Ravulapalem' },
    { id: 123, name: 'Rayachoti' },
    { id: 124, name: 'Rayadurg' },
    { id: 125, name: 'Samalkot' },
    { id: 126, name: 'Sattenapalle' },
    { id: 127, name: 'Srikakulam' },
    { id: 128, name: 'Srikalahasti' },
    { id: 129, name: 'Srisailam' },
    { id: 130, name: 'Sullurpeta' },
    { id: 131, name: 'Tadepalligudem' },
    { id: 132, name: 'Tadpatri' },
    { id: 133, name: 'Tandur' },
    { id: 134, name: 'Tanuku' },
    { id: 135, name: 'Tenali' },
    { id: 136, name: 'Tirumala' },
    { id: 137, name: 'Tirupati' },
    { id: 138, name: 'Tiruvuru' },
    { id: 139, name: 'Tuni' },
    { id: 140, name: 'Uravakonda' },
    { id: 141, name: 'Venkatagiri' },
    { id: 142, name: 'Vijayawada' },
    { id: 143, name: 'Vinukonda' },
    { id: 144, name: 'Visakhapatnam' },
    { id: 145, name: 'Vizianagaram' },
    { id: 146, name: 'Yemmiganur' },
    { id: 147, name: 'Yerraguntla' },
    { id: 148, name: 'Zahirabad' },
    // Add more places to the dataset
  ];
  return (
    <div>
      <Autocomplete places={places} />
    </div>
  )
}

export default StartToYourFood